export const SET_SINGER = 'SET_SINGER'

export const SET_PLYAING_STATE = 'SET_PLYAING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'
